spring:
  application:
    name: springboot-prometheus
  mvc:
    # 静态资源访问路径前缀
    static-path-pattern: /res/**
  # 静态资源访问目录
  resources:
    static-locations: [classpath:/hello/]
  # mysql数据库连接
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/idata?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      url: jdbc:mysql://10.10.10.81:13306/linkempc?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#      url: jdbc:mysql://10.10.10.72:3306/idata?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      #    url: jdbc:mysql://172.25.90.102:3306/idata?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: "root"
      password: "isafelinkepw@2077"
#      password: "Jiaicecream1"

      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8040
  servlet:
    session:
      timeout: 43200

# 配置监控相关
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 打开 Prometheus 的 Web 访问 Path
  endpoint:
    prometheus: # 可以查看转换以后的数据格式
      enabled: true
    health:     # 可以查看更多的细节
      show-details: always

  metrics:    # 配置指标相关信息
    export:
      prometheus:
        enabled: true


# 远程
MaskRulePath: /home/ysjs3/java/upfile/maskRuleFile
# 用来上传用户定义的规则的目录
#MaskRulePath: D:\\uploadFiles\\maskRuleFile

uploadFolder: /home/ysjs3/java/upfile/
#uploadFolder: D:\\uploadFiles\\
# ??python????

maskLogPath: /home/ysjs3/java/logbacktest/

LocalCodePath : /home/ysjs3/java/code/localVideoMask.py

LiveCodePath: /home/ysjs3/java/code/liveVideoMask.py

InBucketName: idata-video # 文件上传的桶名

OutBucketName: idata-jia # 转码后保存的桶名

HuaWeiLocation: cn-east-3 # 脱敏服务器标识



